<?php
$nome1="João Pedro";
$nome2="Marina Barbosa";
$nome3="Lukas Miguel";
$nome4="Julia Soares";
$idade1=36;
$idade2=26;
$idade3=32;
$idade4=45;
$sexo1="M";
$sexo2="F";
$sexo3="M";
$sexo4="F";
$ensino_superior1="N";
$ensino_superior2="S";
$ensino_superior3="S";
$ensino_superior4="S";
echo "Nome: $nome1 Idade: $idade1 Sexo: $sexo1 Escolaridade: $ensino_superior1 <br>";
echo "Nome: $nome2 Idade: $idade2 Sexo: $sexo2 Escolaridade: $ensino_superior2 <br>";
echo "Nome: $nome3 Idade: $idade3 Sexo: $sexo3 Escolaridade: $ensino_superior3 <br>";
echo "Nome: $nome4 Idade: $idade4 Sexo: $sexo4 Escolaridade: $ensino_superior4 <br>";
?>


